name: otp_server
description: A server app using the shelf package and Docker.
version: 1.0.0
environment:
     sdk: '>=2.0.0 <3.0.0'

dependencies:
  args:
  shelf:
  shelf_router:


dev_dependencies:
  http:


